#ifndef ONIONHEN_DAEMON_ELF
#define ONIONHEN_DAEMON_ELF "../../bin/daemon.elf"
#endif
#ifndef ONIONHEN_UTIL_ELF
#define ONIONHEN_UTIL_ELF "../../bin/util.elf"
#endif
#ifndef ONIONHEN_KSTUFF_ELF
#define ONIONHEN_KSTUFF_ELF "../assets/kstuff.elf"
#endif

__asm__(".intel_syntax noprefix\n"
        ".section .data\n"
        ".global daemon_start\n"
        ".type   daemon_start, @object\n"
        ".align  16\n"
        "daemon_start:\n"
        ".incbin \"" ONIONHEN_DAEMON_ELF "\"\n"
        "daemon_end:\n"
        ".global daemon_size\n"
        ".type   daemon_size, @object\n"
        ".align  4\n"
        "daemon_size:\n"
        ".int    daemon_end - daemon_start\n"

        ".global util_start\n"
        ".type   util_start, @object\n"
        ".align  16\n"
        "util_start:\n"
        ".incbin \"" ONIONHEN_UTIL_ELF "\"\n"
        "util_end:\n"
        ".global util_size\n"
        ".type   util_size, @object\n"
        ".align  4\n"
        "util_size:\n"
        ".int    util_end - util_start\n"

        ".global sicon_start\n"
        ".type   sicon_start, @object\n"
        ".align  16\n"
        "sicon_start:\n"
        ".incbin \"../assets/onionhen_sicon.png\"\n"
        "sicon_end:\n"
        ".global sicon_size\n"
        ".type   sicon_size, @object\n"
        ".align  4\n"
        "sicon_size:\n"
        ".int    sicon_end - sicon_start\n"

        /* Toolbox menu icons → /data/OnionHEN/assets/ (XML uses //user//data//...) */
        ".global icon_xml_package_start\n"
        ".type   icon_xml_package_start, @object\n"
        ".align  16\n"
        "icon_xml_package_start:\n"
        ".incbin \"../assets/icon_xml_package.png\"\n"
        "icon_xml_package_end:\n"
        ".global icon_xml_package_size\n"
        ".type   icon_xml_package_size, @object\n"
        ".align  4\n"
        "icon_xml_package_size:\n"
        ".int    icon_xml_package_end - icon_xml_package_start\n"

        ".global icon_xml_plugins_start\n"
        ".type   icon_xml_plugins_start, @object\n"
        ".align  16\n"
        "icon_xml_plugins_start:\n"
        ".incbin \"../assets/icon_xml_plugins.png\"\n"
        "icon_xml_plugins_end:\n"
        ".global icon_xml_plugins_size\n"
        ".type   icon_xml_plugins_size, @object\n"
        ".align  4\n"
        "icon_xml_plugins_size:\n"
        ".int    icon_xml_plugins_end - icon_xml_plugins_start\n"

        ".global icon_xml_game_start\n"
        ".type   icon_xml_game_start, @object\n"
        ".align  16\n"
        "icon_xml_game_start:\n"
        ".incbin \"../assets/icon_xml_game.png\"\n"
        "icon_xml_game_end:\n"
        ".global icon_xml_game_size\n"
        ".type   icon_xml_game_size, @object\n"
        ".align  4\n"
        "icon_xml_game_size:\n"
        ".int    icon_xml_game_end - icon_xml_game_start\n"

        ".global icon_xml_network_start\n"
        ".type   icon_xml_network_start, @object\n"
        ".align  16\n"
        "icon_xml_network_start:\n"
        ".incbin \"../assets/icon_xml_network.png\"\n"
        "icon_xml_network_end:\n"
        ".global icon_xml_network_size\n"
        ".type   icon_xml_network_size, @object\n"
        ".align  4\n"
        "icon_xml_network_size:\n"
        ".int    icon_xml_network_end - icon_xml_network_start\n"

        ".global icon_xml_settings_start\n"
        ".type   icon_xml_settings_start, @object\n"
        ".align  16\n"
        "icon_xml_settings_start:\n"
        ".incbin \"../assets/icon_xml_settings.png\"\n"
        "icon_xml_settings_end:\n"
        ".global icon_xml_settings_size\n"
        ".type   icon_xml_settings_size, @object\n"
        ".align  4\n"
        "icon_xml_settings_size:\n"
        ".int    icon_xml_settings_end - icon_xml_settings_start\n"

        ".global icon_xml_shortcuts_start\n"
        ".type   icon_xml_shortcuts_start, @object\n"
        ".align  16\n"
        "icon_xml_shortcuts_start:\n"
        ".incbin \"../assets/icon_xml_shortcuts.png\"\n"
        "icon_xml_shortcuts_end:\n"
        ".global icon_xml_shortcuts_size\n"
        ".type   icon_xml_shortcuts_size, @object\n"
        ".align  4\n"
        "icon_xml_shortcuts_size:\n"
        ".int    icon_xml_shortcuts_end - icon_xml_shortcuts_start\n"

        ".global icon_xml_debug_start\n"
        ".type   icon_xml_debug_start, @object\n"
        ".align  16\n"
        "icon_xml_debug_start:\n"
        ".incbin \"../assets/icon_xml_debug.png\"\n"
        "icon_xml_debug_end:\n"
        ".global icon_xml_debug_size\n"
        ".type   icon_xml_debug_size, @object\n"
        ".align  4\n"
        "icon_xml_debug_size:\n"
        ".int    icon_xml_debug_end - icon_xml_debug_start\n"

        ".global icon_xml_about_start\n"
        ".type   icon_xml_about_start, @object\n"
        ".align  16\n"
        "icon_xml_about_start:\n"
        ".incbin \"../assets/icon_xml_about.png\"\n"
        "icon_xml_about_end:\n"
        ".global icon_xml_about_size\n"
        ".type   icon_xml_about_size, @object\n"
        ".align  4\n"
        "icon_xml_about_size:\n"
        ".int    icon_xml_about_end - icon_xml_about_start\n"
    ".global kstuff_start\n"
    ".type   kstuff_start, @object\n"
    ".align  16\n"
    "kstuff_start:\n"
    ".incbin \"" ONIONHEN_KSTUFF_ELF "\"\n"
    "kstuff_end:\n"
    ".global kstuff_size\n"
    ".type  kstuff_size, @object\n"
    ".align  4\n"
    "kstuff_size:\n"
    ".int    kstuff_end - kstuff_start\n"

    ".global fps_prx_start\n"
    ".type   fps_prx_start, @object\n"
    ".align  16\n"
    "fps_prx_start:\n"
    ".incbin \"../assets/fps.prx\"\n"
    "fps_prx_end:\n"
    ".global fps_prx_size\n"
    ".type  fps_prx_size, @object\n"
    ".align  4\n"
    "fps_prx_size:\n"
    ".int    fps_prx_end - fps_prx_start\n"
);
